<?php
echo json_encode([
    'REQUEST_METHOD' => $_SERVER['REQUEST_METHOD'] ?? 'MISSING',
    'REQUEST_URI' => $_SERVER['REQUEST_URI'] ?? 'MISSING',
    'SCRIPT_NAME' => $_SERVER['SCRIPT_NAME'] ?? 'MISSING',
    'HTTP_X_FORWARDED_PROTO' => $_SERVER['HTTP_X_FORWARDED_PROTO'] ?? 'MISSING',
]);
